//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment1.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string aboutapp {
            get {
                return ResourceManager.GetString("aboutapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos in this album.
        /// </summary>
        public static string albumCount {
            get {
                return ResourceManager.GetString("albumCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string albums {
            get {
                return ResourceManager.GetString("albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photoFrame is a Windows Phone application which will allow the user to browse Picasa albums on his/her Windows Phone (using the JSON) and also allows to take pictures and upload them to Picasa.
        /// </summary>
        public static string appDetails {
            get {
                return ResourceManager.GetString("appDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photoFrame.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        public static string btnSignIn {
            get {
                return ResourceManager.GetString("btnSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to camera.
        /// </summary>
        public static string camera {
            get {
                return ResourceManager.GetString("camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take a picture.
        /// </summary>
        public static string cameraBtn {
            get {
                return ResourceManager.GetString("cameraBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your credentials.
        /// </summary>
        public static string chkSaveCred {
            get {
                return ResourceManager.GetString("chkSaveCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not delete the photo now. Please try again later..
        /// </summary>
        public static string deleteError {
            get {
                return ResourceManager.GetString("deleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your photo has been deleted.
        /// </summary>
        public static string deletephoto {
            get {
                return ResourceManager.GetString("deletephoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picasa authenication failed. Check your email/Password.
        /// </summary>
        public static string errMsgAuthFail {
            get {
                return ResourceManager.GetString("errMsgAuthFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load images from Picasa Server - JSON parsing error happened!.
        /// </summary>
        public static string errMsgJSONError1 {
            get {
                return ResourceManager.GetString("errMsgJSONError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get albums data from Picasa server!.
        /// </summary>
        public static string errMsgPicasaServer1 {
            get {
                return ResourceManager.GetString("errMsgPicasaServer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string lblForgotPwd {
            get {
                return ResourceManager.GetString("lblForgotPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon with Google....
        /// </summary>
        public static string lblLogon {
            get {
                return ResourceManager.GetString("lblLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email-Id.
        /// </summary>
        public static string msgInvalidemail {
            get {
                return ResourceManager.GetString("msgInvalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password.
        /// </summary>
        public static string msgInvalidUser {
            get {
                return ResourceManager.GetString("msgInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged on with.
        /// </summary>
        public static string msgLoginSuccess {
            get {
                return ResourceManager.GetString("msgLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photoFrame.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Uploaded.
        /// </summary>
        public static string photouploaded {
            get {
                return ResourceManager.GetString("photouploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr.
        /// </summary>
        public static string rFlickr {
            get {
                return ResourceManager.GetString("rFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picasa.
        /// </summary>
        public static string rPicasa {
            get {
                return ResourceManager.GetString("rPicasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New photos will be notified here.
        /// </summary>
        public static string TileNotification {
            get {
                return ResourceManager.GetString("TileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload a photo.
        /// </summary>
        public static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.0.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
